# Generated by Django 5.2.4 on 2026-04-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Viewer', 'viewer'), ('Analyst', 'analyst'), ('Admin', 'admin')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
